name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: walber7/hello-mundo:latest
 
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: sh /app/hello.sh
